### ISSUE TITLE
Caffe version?

### ISSUE THREAD

**Issue by u39kun** [yulequan/3D-Caffe#1]
Thank you for sharing this.
Do you happen to have the git hash of Caffe that this version of Caffe was forked from?  

Just curious... are you familiar / connected with the work being done here?
https://github.com/facebook/C3D

**Comment by yulequan** [comment]
The git hash is 4541f8900588a335f2d9387a5b03460deba68678.

I have used the previous version of C3D.

**Comment by u39kun** [comment]
Ok, thanks for the info.
