### ISSUE TITLE
can not use cuDNN acceleration?

### ISSUE THREAD

**Issue by steve-xipeng** [yulequan/3D-Caffe#3]
There are some errors when I uncomment USE_CUDNN := 1 and then make all -j8:

In file included from ./include/caffe/util/device_alternate.hpp:40:0,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/layers/absval_layer.hpp:6,
                 from src/caffe/layers/absval_layer.cpp:3:
./include/caffe/util/cudnn.hpp: In function ‘void caffe::cudnn::createPoolingDesc(cudnnPoolingStruct**, caffe::PoolingParameter_PoolMethod, cudnnPoolingMode_t*, int, int, int, int, int, int)’:
./include/caffe/util/cudnn.hpp:127:41: error: too few arguments to function ‘cudnnStatus_t cudnnSetPooling2dDescriptor(cudnnPoolingDescriptor_t, cudnnPoolingMode_t, cudnnNanPropagation_t, int, int, int, int, int, int)’
         pad_h, pad_w, stride_h, stride_w));
                                         ^
./include/caffe/util/cudnn.hpp:15:28: note: in definition of macro ‘CUDNN_CHECK’
     cudnnStatus_t status = condition; \
                            ^
In file included from ./include/caffe/util/cudnn.hpp:5:0,
                 from ./include/caffe/util/device_alternate.hpp:40,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/layers/absval_layer.hpp:6,
                 from src/caffe/layers/absval_layer.cpp:3:
/usr/local/cuda/include/cudnn.h:803:27: note: declared here
 cudnnStatus_t CUDNNWINAPI cudnnSetPooling2dDescriptor(
                           ^
make: *** [.build_release/src/caffe/layers/absval_layer.o] Error 1

The error is gone when USE_CUDNN := 1 is commented.
How can I fix this if I want to use cuDNN acceleration?

**Comment by yulequan** [comment]
Currently, this code use the orginal GPU implementation of 3D convolution. It does not support the cuDNN acceleration.  I will work on cuDNN acceleration these days.
