### ISSUE TITLE
about 3D Pooling in （x,y,z）

### ISSUE THREAD

**Issue by robotzheng** [yulequan/3D-Caffe#4]
x != y != z, how can set the pooling_param?

**Comment by yulequan** [comment]
You can use kernel_size  three times, like 
{ kernel_size: 3
  kernel_size: 4
  kernel_size: 5
}

**Comment by robotzheng** [comment]
message PoolingNDParameter {
 935   enum PoolMethod {
 936     MAX = 0;
 937     AVE = 1;
 938     STOCHASTIC = 2;
 939   }
 940   optional PoolMethod pool = 1 [default = MAX]; // The pooling method
 941   // Pad, kernel size, and stride are all given as a single value for equal
 942   // dimensions in all spatial dimensions, or once per spatial dimension.
 943   repeated uint32 pad = 2; // The padding size defaults to 0
 944   repeated uint32 kernel_size = 3; // The kernel size (square)
 945   repeated uint32 stride = 4; // defaults to 1
 946 
 947   // For 2D pooling only, the *_h and *_w versions may also be used to
 948   // specify both spatial dimensions.
 949   optional uint32 pad_h = 5 [default = 0]; // The padding height (2D only)
 950   optional uint32 pad_w = 6 [default = 0]; // The padding width (2D only)
 951   optional uint32 kernel_h = 7; // The kernel height (2D only)
 952   optional uint32 kernel_w = 8; // The kernel width (2D only)
 953   optional uint32 stride_h = 9; // The stride height (2D only)
 954   optional uint32 stride_w = 10; // The stride width (2D only)
 955   enum Engine {
 956     DEFAULT = 0;
 957     CAFFE = 1;
 958     CUDNN = 2;
 959   }
 960   optional Engine engine = 11 [default = DEFAULT];
 961   // If global_pooling then it will pool over the size of the bottom by doing
 962   // kernel_h = bottom->height and kernel_w = bottom->width
 963   optional bool global_pooling = 12 [default = false];
 964   // The axis to interpret as "channels" when performing pooling.
 965   // Preceding dimensions are treated as independent inputs;
 966   // succeeding dimensions are treated as "spatial".
 967   optional int32 axis = 13 [default = 1];
 968 }

caffe.proto not changed, when I use kernel_size three times, report error.

**Comment by yulequan** [comment]
I can use kernel_size three times. Did you use "pooling_nd_param" in the prototxt?
![image](https://cloud.githubusercontent.com/assets/10140621/24408071/aa92c372-139a-11e7-8aab-0902f9c2f42e.png)
