### ISSUE TITLE
training lung cancer dicom slices data using 3D-Caffe

### ISSUE THREAD

**Issue by robotzheng** [yulequan/3D-Caffe#5]
my data are 120*120*120, using 8 convs and 1 pooling to train, guassian init, but it can't convergence. 
any suggestions？
Thanks.

**Comment by robotzheng** [comment]
using bilinear_3D is also not convergence, the other initialized methods are not enable.

**Comment by yulequan** [comment]
Did you train segmentation network or use upsampling layers?

**Comment by robotzheng** [comment]
lung cancer classification is a dichotomy, not segmentation. I write a new network like VGG.

**Comment by yulequan** [comment]
I think you can use guassian init with a smaller learning rate and more pooling layers

**Comment by robotzheng** [comment]
0330 10:30:01.119685  3982 hdf5_data_layer.cpp:116] Number of HDF5 files: 23
I0330 10:30:01.121150  3982 hdf5.cpp:32] Datatype class: H5T_FLOAT
I0330 10:30:01.745815  3982 net.cpp:150] Setting up data
I0330 10:30:01.745882  3982 net.cpp:157] Top shape: 4 1 120 120 120 (6912000)
I0330 10:30:01.745894  3982 net.cpp:157] Top shape: 4 1 1 1 1 (4)
I0330 10:30:01.745925  3982 net.cpp:165] Memory required for data: 27648016
I0330 10:30:01.745937  3982 layer_factory.hpp:77] Creating layer conv0_conv
I0330 10:30:01.745995  3982 net.cpp:106] Creating Layer conv0_conv
I0330 10:30:01.746011  3982 net.cpp:454] conv0_conv <- data
I0330 10:30:01.746031  3982 net.cpp:411] conv0_conv -> conv0_conv
I0330 10:30:01.748656  3982 net.cpp:150] Setting up conv0_conv
I0330 10:30:01.748683  3982 net.cpp:157] Top shape: 4 32 59 59 59 (26288512)
I0330 10:30:01.748699  3982 net.cpp:165] Memory required for data: 132802064
I0330 10:30:01.748730  3982 layer_factory.hpp:77] Creating layer conv0
I0330 10:30:01.748751  3982 net.cpp:106] Creating Layer conv0
I0330 10:30:01.748764  3982 net.cpp:454] conv0 <- conv0_conv
I0330 10:30:01.748775  3982 net.cpp:411] conv0 -> conv0
I0330 10:30:01.749908  3982 net.cpp:150] Setting up conv0
I0330 10:30:01.749939  3982 net.cpp:157] Top shape: 4 32 59 59 59 (26288512)
I0330 10:30:01.749951  3982 net.cpp:165] Memory required for data: 237956112
I0330 10:30:01.749970  3982 layer_factory.hpp:77] Creating layer conv0_scale
I0330 10:30:01.749999  3982 net.cpp:106] Creating Layer conv0_scale
I0330 10:30:01.750011  3982 net.cpp:454] conv0_scale <- conv0
I0330 10:30:01.750022  3982 net.cpp:397] conv0_scale -> conv0 (in-place)
I0330 10:30:01.750092  3982 layer_factory.hpp:77] Creating layer conv0_scale
I0330 10:30:01.752095  3982 net.cpp:150] Setting up conv0_scale
I0330 10:30:01.752117  3982 net.cpp:157] Top shape: 4 32 59 59 59 (26288512)
I0330 10:30:01.752130  3982 net.cpp:165] Memory required for data: 343110160
I0330 10:30:01.752144  3982 layer_factory.hpp:77] Creating layer conv0_relu
I0330 10:30:01.752164  3982 net.cpp:106] Creating Layer conv0_relu
I0330 10:30:01.752177  3982 net.cpp:454] conv0_relu <- conv0
I0330 10:30:01.752187  3982 net.cpp:397] conv0_relu -> conv0 (in-place)
I0330 10:30:01.752213  3982 net.cpp:150] Setting up conv0_relu
I0330 10:30:01.752228  3982 net.cpp:157] Top shape: 4 32 59 59 59 (26288512)
I0330 10:30:01.752234  3982 net.cpp:165] Memory required for data: 448264208
I0330 10:30:01.752244  3982 layer_factory.hpp:77] Creating layer conv1a_conv
I0330 10:30:01.752261  3982 net.cpp:106] Creating Layer conv1a_conv
I0330 10:30:01.752275  3982 net.cpp:454] conv1a_conv <- conv0
I0330 10:30:01.752291  3982 net.cpp:411] conv1a_conv -> conv1a_conv
I0330 10:30:01.754570  3982 net.cpp:150] Setting up conv1a_conv
I0330 10:30:01.754595  3982 net.cpp:157] Top shape: 4 32 59 59 59 (26288512)
I0330 10:30:01.754603  3982 net.cpp:165] Memory required for data: 553418256
I0330 10:30:01.754624  3982 layer_factory.hpp:77] Creating layer conv1b
I0330 10:30:01.754643  3982 net.cpp:106] Creating Layer conv1b
I0330 10:30:01.754654  3982 net.cpp:454] conv1b <- conv1a_conv
I0330 10:30:01.754670  3982 net.cpp:411] conv1b -> conv1b
I0330 10:30:01.755827  3982 net.cpp:150] Setting up conv1b
I0330 10:30:01.755848  3982 net.cpp:157] Top shape: 4 32 59 59 59 (26288512)
I0330 10:30:01.755861  3982 net.cpp:165] Memory required for data: 658572304
I0330 10:30:01.755877  3982 layer_factory.hpp:77] Creating layer conv1b_scale
I0330 10:30:01.755897  3982 net.cpp:106] Creating Layer conv1b_scale
I0330 10:30:01.755909  3982 net.cpp:454] conv1b_scale <- conv1b
I0330 10:30:01.755920  3982 net.cpp:397] conv1b_scale -> conv1b (in-place)
I0330 10:30:01.755978  3982 layer_factory.hpp:77] Creating layer conv1b_scale
I0330 10:30:01.757979  3982 net.cpp:150] Setting up conv1b_scale
I0330 10:30:01.758002  3982 net.cpp:157] Top shape: 4 32 59 59 59 (26288512)
I0330 10:30:01.758010  3982 net.cpp:165] Memory required for data: 763726352
I0330 10:30:01.758028  3982 layer_factory.hpp:77] Creating layer conv1b_relu
I0330 10:30:01.758044  3982 net.cpp:106] Creating Layer conv1b_relu
I0330 10:30:01.758057  3982 net.cpp:454] conv1b_relu <- conv1b
I0330 10:30:01.758067  3982 net.cpp:397] conv1b_relu -> conv1b (in-place)
I0330 10:30:01.758080  3982 net.cpp:150] Setting up conv1b_relu
I0330 10:30:01.758098  3982 net.cpp:157] Top shape: 4 32 59 59 59 (26288512)
I0330 10:30:01.758108  3982 net.cpp:165] Memory required for data: 868880400
I0330 10:30:01.758116  3982 layer_factory.hpp:77] Creating layer conv1c_conv
I0330 10:30:01.758137  3982 net.cpp:106] Creating Layer conv1c_conv
I0330 10:30:01.758148  3982 net.cpp:454] conv1c_conv <- conv1b
I0330 10:30:01.758160  3982 net.cpp:411] conv1c_conv -> conv1c_conv
I0330 10:30:01.758970  3982 net.cpp:150] Setting up conv1c_conv
I0330 10:30:01.758987  3982 net.cpp:157] Top shape: 4 64 30 30 30 (6912000)
I0330 10:30:01.758999  3982 net.cpp:165] Memory required for data: 896528400
I0330 10:30:01.759009  3982 layer_factory.hpp:77] Creating layer conv2a
I0330 10:30:01.759027  3982 net.cpp:106] Creating Layer conv2a
I0330 10:30:01.759037  3982 net.cpp:454] conv2a <- conv1c_conv
I0330 10:30:01.759052  3982 net.cpp:411] conv2a -> conv2a
I0330 10:30:01.759254  3982 net.cpp:150] Setting up conv2a
I0330 10:30:01.759269  3982 net.cpp:157] Top shape: 4 64 30 30 30 (6912000)
I0330 10:30:01.759276  3982 net.cpp:165] Memory required for data: 924176400
I0330 10:30:01.759306  3982 layer_factory.hpp:77] Creating layer conv2a_scale
I0330 10:30:01.759321  3982 net.cpp:106] Creating Layer conv2a_scale
I0330 10:30:01.759330  3982 net.cpp:454] conv2a_scale <- conv2a
I0330 10:30:01.759341  3982 net.cpp:397] conv2a_scale -> conv2a (in-place)
I0330 10:30:01.759402  3982 layer_factory.hpp:77] Creating layer conv2a_scale
I0330 10:30:01.759551  3982 net.cpp:150] Setting up conv2a_scale
I0330 10:30:01.759567  3982 net.cpp:157] Top shape: 4 64 30 30 30 (6912000)
I0330 10:30:01.759574  3982 net.cpp:165] Memory required for data: 951824400
I0330 10:30:01.759590  3982 layer_factory.hpp:77] Creating layer conv2a_relu
I0330 10:30:01.759606  3982 net.cpp:106] Creating Layer conv2a_relu
I0330 10:30:01.759620  3982 net.cpp:454] conv2a_relu <- conv2a
I0330 10:30:01.759630  3982 net.cpp:397] conv2a_relu -> conv2a (in-place)
I0330 10:30:01.759644  3982 net.cpp:150] Setting up conv2a_relu
I0330 10:30:01.759656  3982 net.cpp:157] Top shape: 4 64 30 30 30 (6912000)
I0330 10:30:01.759668  3982 net.cpp:165] Memory required for data: 979472400
I0330 10:30:01.759676  3982 layer_factory.hpp:77] Creating layer conv2b_conv
I0330 10:30:01.759697  3982 net.cpp:106] Creating Layer conv2b_conv
I0330 10:30:01.759707  3982 net.cpp:454] conv2b_conv <- conv2a
I0330 10:30:01.759719  3982 net.cpp:411] conv2b_conv -> conv2b_conv
I0330 10:30:01.761948  3982 net.cpp:150] Setting up conv2b_conv
I0330 10:30:01.761970  3982 net.cpp:157] Top shape: 4 64 30 30 30 (6912000)
I0330 10:30:01.761982  3982 net.cpp:165] Memory required for data: 1007120400
I0330 10:30:01.761996  3982 layer_factory.hpp:77] Creating layer conv2c
I0330 10:30:01.762015  3982 net.cpp:106] Creating Layer conv2c
I0330 10:30:01.762025  3982 net.cpp:454] conv2c <- conv2b_conv
I0330 10:30:01.762040  3982 net.cpp:411] conv2c -> conv2c
I0330 10:30:01.762259  3982 net.cpp:150] Setting up conv2c
I0330 10:30:01.762274  3982 net.cpp:157] Top shape: 4 64 30 30 30 (6912000)
I0330 10:30:01.762281  3982 net.cpp:165] Memory required for data: 1034768400
I0330 10:30:01.762296  3982 layer_factory.hpp:77] Creating layer conv2c_scale
I0330 10:30:01.762315  3982 net.cpp:106] Creating Layer conv2c_scale
I0330 10:30:01.762326  3982 net.cpp:454] conv2c_scale <- conv2c
I0330 10:30:01.762339  3982 net.cpp:397] conv2c_scale -> conv2c (in-place)
I0330 10:30:01.762398  3982 layer_factory.hpp:77] Creating layer conv2c_scale
I0330 10:30:01.763363  3982 net.cpp:150] Setting up conv2c_scale
I0330 10:30:01.763386  3982 net.cpp:157] Top shape: 4 64 30 30 30 (6912000)
I0330 10:30:01.763393  3982 net.cpp:165] Memory required for data: 1062416400
I0330 10:30:01.763408  3982 layer_factory.hpp:77] Creating layer conv2c_relu
I0330 10:30:01.763428  3982 net.cpp:106] Creating Layer conv2c_relu
I0330 10:30:01.763442  3982 net.cpp:454] conv2c_relu <- conv2c
I0330 10:30:01.763453  3982 net.cpp:397] conv2c_relu -> conv2c (in-place)
I0330 10:30:01.763468  3982 net.cpp:150] Setting up conv2c_relu
I0330 10:30:01.763480  3982 net.cpp:157] Top shape: 4 64 30 30 30 (6912000)
I0330 10:30:01.763494  3982 net.cpp:165] Memory required for data: 1090064400
I0330 10:30:01.763504  3982 layer_factory.hpp:77] Creating layer conv2c_conv
I0330 10:30:01.763521  3982 net.cpp:106] Creating Layer conv2c_conv
I0330 10:30:01.763535  3982 net.cpp:454] conv2c_conv <- conv2c
I0330 10:30:01.763551  3982 net.cpp:411] conv2c_conv -> conv2c_conv
I0330 10:30:01.767693  3982 net.cpp:150] Setting up conv2c_conv
I0330 10:30:01.767724  3982 net.cpp:157] Top shape: 4 128 15 15 15 (1728000)
I0330 10:30:01.767736  3982 net.cpp:165] Memory required for data: 1096976400
I0330 10:30:01.767750  3982 layer_factory.hpp:77] Creating layer conv3a
I0330 10:30:01.767776  3982 net.cpp:106] Creating Layer conv3a
I0330 10:30:01.767787  3982 net.cpp:454] conv3a <- conv2c_conv
I0330 10:30:01.767799  3982 net.cpp:411] conv3a -> conv3a
I0330 10:30:01.767987  3982 net.cpp:150] Setting up conv3a
I0330 10:30:01.768002  3982 net.cpp:157] Top shape: 4 128 15 15 15 (1728000)
I0330 10:30:01.768008  3982 net.cpp:165] Memory required for data: 1103888400
I0330 10:30:01.768033  3982 layer_factory.hpp:77] Creating layer conv3a_scale
I0330 10:30:01.768048  3982 net.cpp:106] Creating Layer conv3a_scale
I0330 10:30:01.768056  3982 net.cpp:454] conv3a_scale <- conv3a
I0330 10:30:01.768069  3982 net.cpp:397] conv3a_scale -> conv3a (in-place)
I0330 10:30:01.768121  3982 layer_factory.hpp:77] Creating layer conv3a_scale
I0330 10:30:01.768229  3982 net.cpp:150] Setting up conv3a_scale
I0330 10:30:01.768244  3982 net.cpp:157] Top shape: 4 128 15 15 15 (1728000)
I0330 10:30:01.768250  3982 net.cpp:165] Memory required for data: 1110800400
I0330 10:30:01.768261  3982 layer_factory.hpp:77] Creating layer conv3a_relu
I0330 10:30:01.768278  3982 net.cpp:106] Creating Layer conv3a_relu
I0330 10:30:01.768291  3982 net.cpp:454] conv3a_relu <- conv3a
I0330 10:30:01.768306  3982 net.cpp:397] conv3a_relu -> conv3a (in-place)
I0330 10:30:01.768321  3982 net.cpp:150] Setting up conv3a_relu
I0330 10:30:01.768333  3982 net.cpp:157] Top shape: 4 128 15 15 15 (1728000)
I0330 10:30:01.768344  3982 net.cpp:165] Memory required for data: 1117712400
I0330 10:30:01.768357  3982 layer_factory.hpp:77] Creating layer conv3b_conv
I0330 10:30:01.768385  3982 net.cpp:106] Creating Layer conv3b_conv
I0330 10:30:01.768396  3982 net.cpp:454] conv3b_conv <- conv3a
I0330 10:30:01.768409  3982 net.cpp:411] conv3b_conv -> conv3b_conv
I0330 10:30:01.774417  3982 net.cpp:150] Setting up conv3b_conv
I0330 10:30:01.774446  3982 net.cpp:157] Top shape: 4 128 15 15 15 (1728000)
I0330 10:30:01.774462  3982 net.cpp:165] Memory required for data: 1124624400
I0330 10:30:01.774477  3982 layer_factory.hpp:77] Creating layer conv3c
I0330 10:30:01.774497  3982 net.cpp:106] Creating Layer conv3c
I0330 10:30:01.774511  3982 net.cpp:454] conv3c <- conv3b_conv
I0330 10:30:01.774523  3982 net.cpp:411] conv3c -> conv3c
I0330 10:30:01.774730  3982 net.cpp:150] Setting up conv3c
I0330 10:30:01.774746  3982 net.cpp:157] Top shape: 4 128 15 15 15 (1728000)
I0330 10:30:01.774755  3982 net.cpp:165] Memory required for data: 1131536400
I0330 10:30:01.774776  3982 layer_factory.hpp:77] Creating layer conv3c_scale
I0330 10:30:01.774791  3982 net.cpp:106] Creating Layer conv3c_scale
I0330 10:30:01.774802  3982 net.cpp:454] conv3c_scale <- conv3c
I0330 10:30:01.774811  3982 net.cpp:397] conv3c_scale -> conv3c (in-place)
I0330 10:30:01.774868  3982 layer_factory.hpp:77] Creating layer conv3c_scale
I0330 10:30:01.774984  3982 net.cpp:150] Setting up conv3c_scale
I0330 10:30:01.774998  3982 net.cpp:157] Top shape: 4 128 15 15 15 (1728000)
I0330 10:30:01.775005  3982 net.cpp:165] Memory required for data: 1138448400
I0330 10:30:01.775018  3982 layer_factory.hpp:77] Creating layer conv3c_relu
I0330 10:30:01.775029  3982 net.cpp:106] Creating Layer conv3c_relu
I0330 10:30:01.775046  3982 net.cpp:454] conv3c_relu <- conv3c
I0330 10:30:01.775061  3982 net.cpp:397] conv3c_relu -> conv3c (in-place)
I0330 10:30:01.775077  3982 net.cpp:150] Setting up conv3c_relu
I0330 10:30:01.775089  3982 net.cpp:157] Top shape: 4 128 15 15 15 (1728000)
I0330 10:30:01.775100  3982 net.cpp:165] Memory required for data: 1145360400
I0330 10:30:01.775113  3982 layer_factory.hpp:77] Creating layer conv3c_conv
I0330 10:30:01.775135  3982 net.cpp:106] Creating Layer conv3c_conv
I0330 10:30:01.775148  3982 net.cpp:454] conv3c_conv <- conv3c
I0330 10:30:01.775163  3982 net.cpp:411] conv3c_conv -> conv3c_conv
I0330 10:30:01.786633  3982 net.cpp:150] Setting up conv3c_conv
I0330 10:30:01.786655  3982 net.cpp:157] Top shape: 4 256 8 8 8 (524288)
I0330 10:30:01.786672  3982 net.cpp:165] Memory required for data: 1147457552
I0330 10:30:01.786689  3982 layer_factory.hpp:77] Creating layer conv8a
I0330 10:30:01.786712  3982 net.cpp:106] Creating Layer conv8a
I0330 10:30:01.786728  3982 net.cpp:454] conv8a <- conv3c_conv
I0330 10:30:01.786739  3982 net.cpp:411] conv8a -> conv8a
I0330 10:30:01.786936  3982 net.cpp:150] Setting up conv8a
I0330 10:30:01.786952  3982 net.cpp:157] Top shape: 4 256 8 8 8 (524288)
I0330 10:30:01.786959  3982 net.cpp:165] Memory required for data: 1149554704
I0330 10:30:01.786973  3982 layer_factory.hpp:77] Creating layer conv8a_scale
I0330 10:30:01.786995  3982 net.cpp:106] Creating Layer conv8a_scale
I0330 10:30:01.787005  3982 net.cpp:454] conv8a_scale <- conv8a
I0330 10:30:01.787019  3982 net.cpp:397] conv8a_scale -> conv8a (in-place)
I0330 10:30:01.787075  3982 layer_factory.hpp:77] Creating layer conv8a_scale
I0330 10:30:01.787178  3982 net.cpp:150] Setting up conv8a_scale
I0330 10:30:01.787192  3982 net.cpp:157] Top shape: 4 256 8 8 8 (524288)
I0330 10:30:01.787200  3982 net.cpp:165] Memory required for data: 1151651856
I0330 10:30:01.787214  3982 layer_factory.hpp:77] Creating layer conv8a_relu
I0330 10:30:01.787231  3982 net.cpp:106] Creating Layer conv8a_relu
I0330 10:30:01.787240  3982 net.cpp:454] conv8a_relu <- conv8a
I0330 10:30:01.787258  3982 net.cpp:397] conv8a_relu -> conv8a (in-place)
I0330 10:30:01.787276  3982 net.cpp:150] Setting up conv8a_relu
I0330 10:30:01.787287  3982 net.cpp:157] Top shape: 4 256 8 8 8 (524288)
I0330 10:30:01.787299  3982 net.cpp:165] Memory required for data: 1153749008
I0330 10:30:01.787309  3982 layer_factory.hpp:77] Creating layer conv10
I0330 10:30:01.787333  3982 net.cpp:106] Creating Layer conv10
I0330 10:30:01.787343  3982 net.cpp:454] conv10 <- conv8a
I0330 10:30:01.787355  3982 net.cpp:411] conv10 -> conv10
I0330 10:30:01.809630  3982 net.cpp:150] Setting up conv10
I0330 10:30:01.809661  3982 net.cpp:157] Top shape: 4 256 8 8 8 (524288)
I0330 10:30:01.809669  3982 net.cpp:165] Memory required for data: 1155846160
I0330 10:30:01.809684  3982 layer_factory.hpp:77] Creating layer bn10
I0330 10:30:01.809707  3982 net.cpp:106] Creating Layer bn10
I0330 10:30:01.809725  3982 net.cpp:454] bn10 <- conv10
I0330 10:30:01.809737  3982 net.cpp:411] bn10 -> bn10
I0330 10:30:01.809932  3982 net.cpp:150] Setting up bn10
I0330 10:30:01.809964  3982 net.cpp:157] Top shape: 4 256 8 8 8 (524288)
I0330 10:30:01.809976  3982 net.cpp:165] Memory required for data: 1157943312
I0330 10:30:01.809991  3982 layer_factory.hpp:77] Creating layer bn10_scale
I0330 10:30:01.810004  3982 net.cpp:106] Creating Layer bn10_scale
I0330 10:30:01.810014  3982 net.cpp:454] bn10_scale <- bn10
I0330 10:30:01.810027  3982 net.cpp:397] bn10_scale -> bn10 (in-place)
I0330 10:30:01.810084  3982 layer_factory.hpp:77] Creating layer bn10_scale
I0330 10:30:01.810190  3982 net.cpp:150] Setting up bn10_scale
I0330 10:30:01.810204  3982 net.cpp:157] Top shape: 4 256 8 8 8 (524288)
I0330 10:30:01.810211  3982 net.cpp:165] Memory required for data: 1160040464
I0330 10:30:01.810223  3982 layer_factory.hpp:77] Creating layer res10_relu
I0330 10:30:01.810246  3982 net.cpp:106] Creating Layer res10_relu
I0330 10:30:01.810261  3982 net.cpp:454] res10_relu <- bn10
I0330 10:30:01.810272  3982 net.cpp:397] res10_relu -> bn10 (in-place)
I0330 10:30:01.810287  3982 net.cpp:150] Setting up res10_relu
I0330 10:30:01.810302  3982 net.cpp:157] Top shape: 4 256 8 8 8 (524288)
I0330 10:30:01.810312  3982 net.cpp:165] Memory required for data: 1162137616
I0330 10:30:01.810322  3982 layer_factory.hpp:77] Creating layer pool0
I0330 10:30:01.810343  3982 net.cpp:106] Creating Layer pool0
I0330 10:30:01.810358  3982 net.cpp:454] pool0 <- bn10
I0330 10:30:01.810374  3982 net.cpp:411] pool0 -> pool0
I0330 10:30:01.810539  3982 net.cpp:150] Setting up pool0
I0330 10:30:01.810554  3982 net.cpp:157] Top shape: 4 256 1 1 1 (1024)
I0330 10:30:01.810562  3982 net.cpp:165] Memory required for data: 1162141712
I0330 10:30:01.810570  3982 layer_factory.hpp:77] Creating layer classifier
I0330 10:30:01.810587  3982 net.cpp:106] Creating Layer classifier
I0330 10:30:01.810597  3982 net.cpp:454] classifier <- pool0
I0330 10:30:01.810611  3982 net.cpp:411] classifier -> classifier
I0330 10:30:01.810714  3982 net.cpp:150] Setting up classifier
I0330 10:30:01.810727  3982 net.cpp:157] Top shape: 4 2 (8)
I0330 10:30:01.810735  3982 net.cpp:165] Memory required for data: 1162141744
I0330 10:30:01.810746  3982 layer_factory.hpp:77] Creating layer loss
I0330 10:30:01.810762  3982 net.cpp:106] Creating Layer loss
I0330 10:30:01.810771  3982 net.cpp:454] loss <- classifier
I0330 10:30:01.810781  3982 net.cpp:454] loss <- label
I0330 10:30:01.810792  3982 net.cpp:411] loss -> loss
I0330 10:30:01.810812  3982 layer_factory.hpp:77] Creating layer loss
I0330 10:30:01.982873  3982 net.cpp:150] Setting up loss
I0330 10:30:01.982921  3982 net.cpp:157] Top shape: (1)
I0330 10:30:01.982933  3982 net.cpp:160]     with loss weight 1
I0330 10:30:01.982971  3982 net.cpp:165] Memory required for data: 1162141748

**Comment by robotzheng** [comment]
I used three conv/2 and one AVE pooling, gaussian lr 0.0001

**Comment by yulequan** [comment]
Maybe you can try a smaller learning rate

**Comment by yulequan** [comment]
The bilinear_3D init is not fit to this case.

**Comment by robotzheng** [comment]
using 1e-6,  not convergence

**Comment by robotzheng** [comment]
find a error： 
I0330 13:51:09.512709  8808 net.cpp:663]     [Forward] Layer data, top blob data data: 4.83853e+16
I0330 13:51:09.512802  8808 net.cpp:663]     [Forward] Layer data, top blob label data: 0.5
input data is not right, 
using the bellow code to write the hdf5 files in python:
def save_hd5py(dataset_dict, destfile):
    f = h5py.File(destfile, mode='w')
    for name, dataset in dataset_dict.iteritems():
        dat = f.create_dataset(name, dataset.shape, dtype=str(dataset.dtype))
        dat[...] = dataset
    f.flush()
    f.close()  

        add_channel_array = np.empty((1, img_size_z, img_size_y, img_size_x), dtype=np.float32)
        add_channel_array[0] = dsetdicom.image_array
        add_label = np.empty((1, 1, 1, 1), dtype=np.float32)
save_hd5py({'data': all_imgs, 'label': all_labels}, fn)

**Comment by robotzheng** [comment]
any suggestions for the hdf5 data making?

**Comment by yulequan** [comment]
I use the matlab script to write the hdf5 data, you can refer: https://github.com/BVLC/caffe/tree/master/matlab/hdf5creation

As for the python, I think we should be careful of the dimension order and the data type.
